### ISSUE TITLE
Document AWS secret manager

### ISSUE THREAD

**Issue by rolandtyler** [ConsenSys/doc.web3signer#115]
Document AWS secret manager including new CLI option `--aws-connection-cache-size`

See https://github.com/ConsenSys/web3signer/issues/531
https://github.com/ConsenSys/web3signer/pull/541

**Comment by georgep9** [comment]
The cacheable feature was added to address performance bottlenecks and optimise key loading. You can set the maximum size of cacheable AWS secret manager connections using the --aws-connection-cache-size option for the eth2 subcommand. Note that the cache hashcode and identifier for initialized aws clients, are based off  AWS_ACCESS_KEY_ID and AWS_REGION ([relevant signers commit](https://github.com/ConsenSys/signers/commit/7de7e6cb2be4e48833f73624cb0a4a55862336fa)).
