### ISSUE TITLE
Bulk load keystore files

### ISSUE THREAD

**Issue by bgravenorst** [ConsenSys/doc.web3signer#117]
This adds 3 new command arguments for the keystore bulk loading on the eth2 subcommand:

--keystores-path The path to a directory storing Eth2 keystore
--keystores-passwords-path The path to a directory with the corresponding passwords file for the keystores.
--keystores-password-file The path to a file that contains the password that all keystores use.

See: https://github.com/ConsenSys/web3signer/pull/569

Note: You need to restart Web3Signer if you want to pick up new keystores in the directory specified using `--keystores-path`.

**Comment by rolandtyler** [comment]
See also https://github.com/ConsenSys/web3signer/pull/553
