### ISSUE TITLE
Clarify supported Java versions

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.web3signer#160]
Reverted a Web3signer Java17 commit due to a bug in Azure support  in eth1 mode

Java 17 can still be used to run Web3signer, it's just it's still compiling against Java 11.And Azure Eth1 mode is technically broken for Java 17 in Web3signer.

Add a note saying something similar to Azure support for SECP256K1 in eth1 mode only works on Java 11 till Azure provide support for it.

Otherwise eth2 mode has no issues with any Java version ... even including latest Java 20

**Comment by alexandratran** [comment]
See https://github.com/Consensys/web3signer/pull/870 for latest update.
