### ISSUE TITLE
Feature documentation: Implement the eth_sendTransaction RPC

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.web3signer#162]
Implement the eth_sendTransaction RPC to sign and encode transactions without the execution layer needing the secp256k1 private key.

See: https://github.com/ConsenSys/web3signer/issues/764

This documentation can be adapted from Ethsigner.

**Comment by alexandratran** [comment]
Fixed by https://github.com/Consensys/doc.web3signer/pull/187
