### ISSUE TITLE
Feature documentation: Implement the eth_accounts RPC

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.web3signer#163]
Implement the eth_accounts RPC in web3signer. This should return all Ethereum accounts associated with the secp256k1 keys that are loaded in web3signer.

See: https://github.com/ConsenSys/web3signer/issues/765

We can probably reuse the Ethsigner documentation.

**Comment by alexandratran** [comment]
fixed by https://github.com/Consensys/doc.web3signer/pull/173
