### ISSUE TITLE
Azure supports multiline secret values in bulk mode.

### ISSUE THREAD

**Issue by bgravenorst** [Consensys/doc.web3signer#184]
Azure support multiline secret values in bulk mode.

See:
- https://github.com/Consensys/web3signer/pull/827
- https://github.com/Consensys/web3signer/issues/780

**Comment by MadelineMurray** [comment]
@usmansaleem - the docs indicate that bulk loading for AWS secrets manager is for consensus layer keys only, but bulk loading for Azure key vault is for execution and consensus layer keys. 

a) Is that correct? 
b) For Azure bulk loading, does the following apply to execution and consensus layer keys? 

```
The Azure bulk load mode supports loading multiple keys from the same secret, if keys
are stored with a line terminating character such as `\n`.
This saves cost when dealing with a large number of keys.
Up to 200 keys can be stored under a secret name.
```

**Comment by MadelineMurray** [comment]
Adding some more context from Uzi: 

The \n seems is supported in eth2 mode (for Azure bulk loading)

In eth1 mode we only perform remote signing from Azure .... the bulk loading is also for remote signing of secp keys, hence '\n' only works in eth2 mode

The semantics of bulkloading is slightly different (for Azure) ... in eth2 mode, we bulk load BLS keys from Azure Secrets. in eth1 mode, we create "Azure keys" connections in bulk mode that can perform remote signing using SECP keys. In remote signing, Web3Signer does not download private keys at all.
