### ISSUE TITLE
Document `eth_signTypedData`

### ISSUE THREAD

**Issue by alexandratran** [Consensys/doc.web3signer#209]
Document the `eth_signTypedData` RPC method on this page: https://docs.web3signer.consensys.net/reference/api/json-rpc.

The official EIP-712 spec might help: https://eips.ethereum.org/EIPS/eip-712#specification-of-the-eth_signtypeddata-json-rpc

See https://github.com/Consensys/web3signer/pull/893.

**Comment by MadelineMurray** [comment]
@bgravenorst - could you assign this one to me please.
