### ISSUE TITLE
Document bulk loading secp keys in AWS for eth1 mode

### ISSUE THREAD

**Issue by alexandratran** [Consensys/doc.web3signer#210]
Document bulk loading secp keys in AWS for eth1 mode. New CLI options:

- --aws-kms-enabled
- --aws-kms-auth-mode
- --aws-kms-access-key-id
- --aws-kms-secret-access-key
- --aws-kms-region
- --aws-endpoint-override
- --aws-kms-tag-names-filter
- --aws-kms-tag-values-filter
- --aws-connection-cache-size

See https://github.com/Consensys/web3signer/pull/889 for more information.

**Comment by MadelineMurray** [comment]
Have added options and am waiting for some guidance from @usmansaleem on the following: 

The [Azure Key Vault docs](https://docs.web3signer.consensys.net/how-to/store-keys-vaults/azure) for Web3Signer indicate:
Register Web3Signer as an application by [authenticating to Azure Key Vault](https://learn.microsoft.com/en-us/azure/key-vault/general/authentication)
Add [signing key in Azure Key Vault](https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-portal#add-a-secret-to-key-vault)
Set of values to take note of to use in Web3Signer

I’m not sure how to map this exactly to AWS KMS but my best guesses are:
Register Web3Signer as an application by [authenticating to AWS KMS](https://docs.aws.amazon.com/kms/latest/developerguide/control-access.html)
Create [key policy for the signing key](https://docs.aws.amazon.com/kms/latest/developerguide/key-policies.html)
Take note of the following to use in Web3Signer: AWS Access Key ID and AWS KMS secret access key.

If you could let me know what I’ve got wrong, or needs adding to my AWS KMS guesses, that’d be great thank you.
