### ISSUE TITLE
Document --set-high-watermark and --remove-high-watermark

### ISSUE THREAD

**Issue by alexandratran** [Consensys/doc.web3signer#214]
Document the new `watermark-repair` options, `--set-high-watermark` and `--remove-high-watermark`, on [this page](https://docs.web3signer.consensys.net/reference/cli/subcommands#watermark-repair). See https://github.com/Consensys/web3signer/pull/912 for more info.

**Comment by ATREAY** [comment]
Hey @alexandratran, can work on this issue if you're not already working on it.

**Comment by alexandratran** [comment]
@ATREAY assigned to you. Thanks!

**Comment by ATREAY** [comment]
Hey @alexandratran, I've included the necessary subcommands. Please take a look whenever you have time, and tell me if any changes are needed.
