### ISSUE TITLE
search for "hashicorp" leads to 404

### ISSUE THREAD

**Issue by macfarla** [Consensys/doc.web3signer#259]
search result is this which is a 404
https://docs.web3signer.consensys.io/how-to/store-keys-vaults/hashicorp
but then if I refresh the page, it loads with the content

I went back to the search, clicked on the result and it's a 404 again. It's weird!

**Comment by alexandratran** [comment]
Looks like Algolia search is indexing old URLs of removed pages, which we've applied client-side redirects to. However when you click on the search result, the redirect doesn't trigger – it only works when you refresh the page. I'm not sure if this an Algolia issue or a redirect issue, maybe both. We can try switching to server-side Vercel redirects and see if that helps...

**Comment by joaniefromtheblock** [comment]
This bug appears to have been resolved. The search leads to the correct page. Closing as resolved
