### ISSUE TITLE
Update launchpad page to use `holesky` instead of `goerli`

### ISSUE THREAD

**Issue by gfukushima** [Consensys/doc.web3signer#261]
Goerli has been shutdown and therefore made our docs outdated. Creating this issue so we update the examples and links to point to the holesky testnet that has replaced goerli.

**Comment by joaniefromtheblock** [comment]
@m4sterbunny, I believe this is the page that needs to be updated: https://docs.web3signer.consensys.io/development/tutorials/load-launchpad-keystores

**Comment by m4sterbunny** [comment]
https://github.com/Consensys/doc.web3signer/pull/267/

**Comment by m4sterbunny** [comment]
@gfukushima pls confirm whether scope is just current docs or backward through versioned docs

**Comment by gfukushima** [comment]
@m4sterbunny looked at your PR, I'd suggest you replace sepolia by holesky as @joaniefromtheblock has suggested. Other than that it lgtm.
