### ISSUE TITLE
Update docs for API renames 

### ISSUE THREAD

**Issue by MadelineMurray** [ConsenSys/doc.web3signer#32]
PR: https://github.com/PegaSysEng/web3signer/pull/197

**Comment by alexandratran** [comment]
The updated REST API is externally linked on this page - https://docs.web3signer.consensys.net/en/latest/Reference/Rest/ - so nothing in the docs needs to be changed.

**Comment by NicolasMassart** [comment]
I agree, nothing to change here thanks to generated API doc.
